project 'CityPickUp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'CityPickUp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CityPickUp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'RevealingSplashView'

end
